//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by talk.rc
//
#define ID_RECONN                       4
#define ID_LOG_DEL                      5
#define ID_LOG_ADD                      6
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_TALKTYPE                    129
#define IDD_ADDRBOOK                    130
#define IDD_CONNECT                     131
#define IDD_LOG                         132
#define IDB_TOOLBAR                     133
#define IDR_TRAYMENU                    134
#define IDD_PAGE_MSG                    135
#define IDD_VIEW                        135
#define IDI_ICON1                       136
#define IDI_ICON2                       137
#define IDI_ICON3                       139
#define IDI_ICON4                       140
#define IDD_CFG_MSG_1                   141
#define IDD_CFG_MSG_2                   142
#define IDD_CFG_MSG_3                   143
#define IDI_DEAD                        144
#define IDI_ACTIVE                      145
#define IDI_TRY                         146
#define IDD_CFG_GENERAL                 154
#define IDD_PERSONAL                    155
#define IDD_CONFIRM                     156
#define IDR_NOTIFY                      159
#define IDR_LOGOUT                      161
#define IDI_NEW                         162
#define IDI_OUT                         163
#define IDI_IN                          164
#define IDI_ICON5                       168
#define IDR_LOGMENU                     174
#define IDC_LIST                        1000
#define IDC_IP                          1001
#define IDC_NAME                        1002
#define IDC_CLEAR                       1003
#define IDC_DELETE                      1004
#define IDC_SAVE                        1005
#define IDC_LVWD                        1007
#define IDC_WELMSG                      1008
#define IDC_CONNECT                     1009
#define IDC_SENDMSG                     1011
#define IDC_WMCHECK                     1012
#define IDC_LWCHECK                     1013
#define IDC_LOGLIST                     1015
#define ID_VIEW                         1016
#define IDC_PM_WM                       1017
#define IDC_REMOTE                      1017
#define IDC_PM_LW                       1018
#define IDC_LOCAL                       1018
#define IDC_PM_BWM                      1019
#define IDC_PM_BLW                      1020
#define IDC_MYNAME                      1021
#define IDC_EDIT                        1023
#define IDC_ENABLE                      1024
#define IDC_ONLY                        1026
#define IDC_NEED                        1027
#define IDC_TIME1                       1028
#define IDC_STARTUP                     1029
#define IDC_BEEP                        1030
#define IDC_TIME2                       1031
#define IDC_LIST1                       1031
#define IDC_NAMELIST                    1031
#define IDC_LVWORD                      1032
#define IDC_ABSMSG                      1032
#define IDC_MAXCONN                     1033
#define IDC_CHECK1                      1034
#define IDC_BABSMSG                     1034
#define IDC_SCHEDULE                    1034
#define IDC_CHECK2                      1035
#define IDC_TIME                        1035
#define IDC_BWELMSG                     1035
#define IDC_TEXT                        1036
#define IDC_SPIN1                       1037
#define IDC_SPIN2                       1038
#define IDC_SPIN3                       1039
#define IDC_RSTATIC                     1039
#define IDC_HOST                        1040
#define IDC_RETRY                       1046
#define IDC_SPIN5                       1047
#define IDC_RETRYINTERVAL               1048
#define IDC_SPIN6                       1049
#define IDC_RETRY2                      1050
#define IDC_EMOTE1                      1050
#define IDC_EMOTE2                      1051
#define IDC_EMOTE3                      1052
#define IDC_EMOTEESC                    1053
#define ID_CONNECT                      32772
#define ID_CUT                          32773
#define ID_COPY                         32774
#define ID_PASTE                        32775
#define ID_SETTING                      32776
#define ID_ADDRBOOK                     32777
#define ID_DISC                         32778
#define ID_BEEP                         32779
#define ID_TALK                         32780
#define ID_LOG                          32781
#define ID_WANTTALK                     32783
#define ID_FONT                         32790
#define ID_BACKCOLOR                    32791
#define ID_HSCROLL                      32793
#define ID_VSCROLL                      32794
#define ID_SAVE                         32795
#define ID_REC                          32796
#define ID_TEST                         32797
#define ID_LOG_ENCRYPT                  32799
#define ID_LOG_MER                      32801
#define ID_LOG_MER_ENC                  32802
#define ID_LOG_ENC                      32803
#define ID_LOG_EXP                      32804
#define ID_LOG_MER2                     32805
#define ID_LOG_DEC                      32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
